version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  db:
    image: postgres:15-alpine
    container_name: splitit-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: splitit
      POSTGRES_PASSWORD: splitit
      POSTGRES_DB: splitit
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: splitit-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
